name: main
on: [push, pull_request]

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          distribution: "graalvm-community"
          version: "latest"
          java-version: "21"
          components: "native-image"
          cache: "sbt"
      - run: sbt scalafmtCheckAll scalafmtSbtCheck
  build:
    name: Build
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
      fail-fast: true
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          distribution: "graalvm-community"
          version: "latest"
          java-version: "21"
          components: "native-image"
          cache: "sbt"
      - run: sbt test graalvm-native-image:packageBin
      - uses: actions/upload-artifact@v4
        with:
          name: tfr-${{ runner.os }}
          path: modules/cli/target/graalvm-native-image/tfr
  release:
    name: Release
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
      fail-fast: true
    runs-on: ${{ matrix.os }}
    needs: [build, checks]
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    steps:
      - id: get_version
        run: |
          echo ${GITHUB_REF/refs\/tags\//}
          echo ::set-output name=version::${GITHUB_REF/refs\/tags\//}
      - uses: actions/download-artifact@v4
        with:
          name: tfr-${{ runner.os }}
      - run: mv tfr tfr-${{ runner.os }}
      - id: upload-release-asset
        uses: softprops/action-gh-release@v1
        with:
          files: tfr-${{ runner.os }}
